XMAKE_ROOT := {root}
XMAKE_PLATLIB := $(XMAKE_ROOT)/platlib
XMAKE_SCRIPTS := $(XMAKE_ROOT)/data/bin
XMAKE_HEADERS := $(XMAKE_ROOT)/data/include
XMAKE_DATA := $(XMAKE_ROOT)/data
XMAKE_METADATA := $(XMAKE_ROOT)/metadata
XMAKE_NULL := $(XMAKE_ROOT)/null
XMAKE_VERSION := {version}
DESTDIR := $(XMAKE_DATA)
include {project}/{makefile}
